# Generated by Django 5.1.2 on 2024-11-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название подуслуги'),
        ),
    ]
