# Generated by Django 5.1.2 on 2024-11-21 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0004_peoplecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplecategory',
            name='category_user',
        ),
        migrations.CreateModel(
            name='PeopleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.peoplecategory')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.servicecategory')),
            ],
        ),
    ]
