# Generated by Django 5.1.2 on 2024-11-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0005_remove_peoplecategory_category_user_peopleservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplecategory',
            name='category_user',
            field=models.ManyToManyField(to='stadium.servicecategory'),
        ),
        migrations.DeleteModel(
            name='PeopleService',
        ),
    ]
